openapi: 3.0.0
info:
  title: Edwardsville Memorial Tracker API
  description: REST API for Edwardsville Memorial Tracker
  version: 0.1.0
  license:
    name: MIT

servers:
  - url: http:localhost:1337/api

paths:
  /memorials:
    get:
      summary: Get all memorials
      tags:
        - Memorials
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/memorials"
              examples:
                Memorials:
                  $ref: "#/components/examples/memorials"

    post:
      summary: Add new memorials
      tags:
        - Memorials
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                memorials:
                  type: array
                  items:
                    $ref: "#/components/schemas/memorialWithoutUuid"
            examples:
              Memorials:
                $ref: "#/components/examples/memorialsWithoudUuid"
      responses:
        "201":
          description: Memorials added successfully

  /memorials/types:
    get:
      summary: Get all memorial types
      tags:
        - Memorial Types
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/memorialTypes"
              examples:
                Memorial Types:
                  $ref: "#/components/examples/memorialTypes"

    post:
      summary: Add new memorial type
      tags:
        - Memorial Types
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/memorialTypes"
            examples:
              Memorial Types:
                $ref: "#/components/examples/memorialTypes"
      responses:
        "201":
          description: Memorial type added successfully

components:
  schemas:
    memorials:
      type: object
      properties:
        type:
          type: string
        attributes:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              value:
                oneOf:
                  - type: string
                  - type: boolean
                  - type: number
        uuid:
          type: string

    memorialsWithoutUuid:
      type: array
      items:
        type: object
        properties:
          type:
            type: string
          attributes:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                value:
                  oneOf:
                    - type: string
                    - type: boolean
                    - type: number

    memorialTypes:
      type: array
      items:
        type: object
        properties:
          name:
            type: string
          attributes:
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                value:
                  oneOf:
                    - type: string
                    - type: boolean
                    - type: number
                required:
                  type: boolean

  examples:
    memorialsWithoutUuid:
      summary: An example of a memorial array
      value:
        memorials:
          - type: Bench
            attributes:
              - name: longitude
                value: -89.955567
              - name: latitude
                value: 38.813762
              - name: donor
                value: John Doe
              - name: Date Placed
                value: January 31, 2018
          - type: Historical Building
            attributes:
              - name: longitude
                value: -90.115567
              - name: latitude
                value: 38.923124
              - name: Public Accessible
                value: true
              - name: Handicap Accessible
                value: false
              - name: Date Built
                value: February 31, 1968
    memorials:
      summary: An example of a memorial array
      value:
        memorials:
          - type: Bench
            attributes:
              - name: longitude
                value: -89.955567
              - name: latitude
                value: 38.813762
              - name: donor
                value: John Doe
              - name: Date Placed
                value: January 31, 2018
            uuid: 8df4867c-fe6e-4f13-a911-d7db66ff715a
          - type: Historical Building
            attributes:
              - name: longitude
                value: -90.115567
              - name: latitude
                value: 38.923124
              - name: Public Accessible
                value: true
              - name: Handicap Accessible
                value: false
              - name: Date Built
                value: February 31, 1968
            uuid: 08f703bd-8d67-4c56-bd35-70c0dd8026c9

    memorialTypes:
      summary: An example of memorial types
      value:
        memorialTypes:
          - name: Bench
            attributes:
              - name: longitude
                value: null
                required: true
              - name: latitude
                value: null
                required: true
              - name: Donor
                value: null
                required: true
              - name: Date Placed
                value: null
                required: true
          - name: Tree
            attributes:
              - name: longitude
                value: null
                required: true
              - name: latitude
                value: null
                required: true
              - name: Donor
                value: null
                required: true
              - name: Date Planted
                value: null
                required: true
              - name: Species
                value: null
                required: false
