openapi: 3.0.0
info:
  title: Edwardsville Memorial Tracker API
  description: REST API for Edwardsville Memorial Tracker
  version: 1.0.0
  license:
    name: MIT

servers:
  - url: server/api

paths:
  /memorials:
    tags:
      - Memorials
    get:
      tags:
        - Memorials
      summary: Get all memorials
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Memorial"
    post:
      tags:
        - Memorials
      summary: Add new memorial
      responses:
        "201":
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Memorial"
  /memorials/{id}:
    delete:
      tags:
        - Memorials
      summary: Delete memorial by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted
  /types:
    get:
      tags:
        - Types
      summary: Get all types
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Type"
    post:
      tags:
        - Types
      summary: Add new type
      responses:
        "201":
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  /types/{id}:
    delete:
      tags:
        - Types
      summary: Delete type by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deleted

components:
  schemas:
    Memorial:
      type: object
      properties:
        id:
          type: string
        typeId:
          type: string

    Type:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
