openapi: 3.0.0
info:
    title: Edwardsville Memorial Tracker API
    description: REST API for Edwardsville Memorial Tracker
    version: 0.1.0
    license:
        name: MIT

servers:
    - url: http:localhost:3000/api
 
paths:
    /memorials:
        get:
            summary: Get all memorials
            tags:
                - memorials
            responses:
                '200': 
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: '#/components/schemas/Memorial'
                                    
    /memorials/{id}:
        get:
            summary: Get memorial by ID
            tags:
                - memorials
            parameters:
                  - in: path
                    name: id
                    schema:
                        type: integer
                    required: true
                    description: Numeric ID of the memorial to get
            responses:
                '200': 
                    description: OK
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Memorial'

components:
    schemas:
        Memorial:
            type: object
            properties:
                id:
                    type: integer
                type:
                    type: string
                donator:
                    type: string
                x-coordinate:
                    type: number
                y-coordinate:
                    type: number

