openapi: 3.0.0
info:
  title: Edwardsville Memorial Tracker API
  description: REST API for Edwardsville Memorial Tracker
  version: 0.1.0
  license:
    name: MIT

servers:
  - url: http:localhost:1337/api

paths:
  /memorials:
    get:
      summary: Get all memorials
      tags:
        - memorials
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Memorial"

components:
  schemas:
    Memorial:
      type: object
      properties:
        id:
          type: integer
        type:
          type: string
        donator:
          type: string
        x-coordinate:
          type: number
        y-coordinate:
          type: number
